### ISSUE TITLE
Editor is not fully in sync when applying custom marks

### ISSUE THREAD

**Issue by fadiquader** [yjs/y-prosemirror#21]
**Describe the bug**
I've created a custom plugin to apply a custom mark for highlighting text, and it turns out when another mark is applied on a selected text that has the custom mark, the mark will be partially applied on the text as shown in the gif below. **Bold** is partially applied on the the other side, while it's fully applied on the side where it was applied.
![prosemirror](https://user-images.githubusercontent.com/23264052/87897708-c0597680-ca7e-11ea-814d-b4559f5537d3.gif)

Here's the code for the custom mark

```
const highlightTextPlugin = shouldHighlight => {
  return new Plugin({
    props: {
      handleKeyDown(view) {
        const { state, dispatch } = view;
        let { schema, selection, storedMarks } = state;
        let { $cursor } = selection;

        const markType = schema.marks[MARK_TEXT_HIGHLIGHT];
        if (!$cursor) return false;

        if (markType.isInSet(storedMarks || $cursor.marks())) {
          if (!shouldHighlight) {
            dispatch(state.tr.removeStoredMark(markType));
          }
        } else {
          if (shouldHighlight) {
            dispatch(state.tr.addStoredMark(markType.create({
              highlightColor: HIGHLIGHT_COLOR
            })));
          }
        }

        return false;
      },
    },
  });
};
 const marks = {
...,
  [MARK_TEXT_HIGHLIGHT]: {
    attrs: {
      highlightColor: '',
    },
    inline: true,
    group: 'inline',
    parseDOM: [
      {
        tag: 'span[style*=background-color]',
        getAttrs: (dom) => {
          const { backgroundColor } = dom.style;
          return {
            highlightColor: backgroundColor,
          };
        },
      },
    ],
    toDOM(node) {
      const { highlightColor } = node.attrs;
      let style = '';
      if (highlightColor) {
        style += `background-color: ${highlightColor};`;
      }
      return ['span', { style }, 0];
    },
  },
}
  const plugins = [
      ySyncPlugin(type),
      yCursorPlugin(provider.current.awareness),
      yUndoPlugin(),
      highlightTextPlugin(shouldHighlight),
]
```

**Comment by dmonad** [comment]
Hi @fadiquader ,

as I explained in the issue template, I need to know the dependency versions. Just recently I published a new Yjs version that might cause this issue. Please help me pinpoint this issue by filling out the issue template so I can reproduce it.

**Comment by fadiquader** [comment]
@dmonad  I'm using 
```
"y-prosemirror": "^0.3.3",
"y-websocket": "^1.3.1",
"yjs": "^13.0.0"
```
on the backend 
```
"y-websocket": "^1.2.5",
"ws": "^7.3.0",
"yjs": "^13.3.0"
```

**Comment by dmonad** [comment]
Okay, here is what you do.. 

Update the packages to install the latest yjs modules:

```sh
npm update
```

and then you give me the exact version numbers you are actually using. You should be at yjs@13.3.0 and y-prosemirror@0.3.5. For example, you could look into `package-lock.json` or you simply do `npm list yjs`.

FYI `^13.0.0` describes a range of versions. Currently, there are 13 versions that match that version description.  https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by dmonad** [comment]
I'm going to close this because I can't reproduce this issue. Just update your packages.

**Comment by fadiquader** [comment]
@dmonad upgraded all packages to the the latest version and that didn't fix it. Anyways it must br my code. 
Thanks

**Comment by dmonad** [comment]
Can you please share your package-lock.json?

**Comment by fadiquader** [comment]
I'm using yarn, so I'll share `yarn.lock`
Backend
https://gist.github.com/fadiquader/17c9a05c202f3b2b71db75e5b7d82712 
Frontend
https://gist.github.com/fadiquader/dd1a5afb54cf84fde7580b1dcafe1e5a
